// Used as test-data. Remove when test-invoices can be fetched from api reliably
export const mockedInvoices = [
  {
    dueDate: '2024-06-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-06-17',
    fromDate: '2024-06-17',
    toDate: '2024-06-17',
    invoiceNumber: '999',
    invoiceStatus: 'PAID',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'PAID',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
  {
    dueDate: '2024-09-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-06-17',
    fromDate: '2024-06-17',
    toDate: '2024-09-17',
    invoiceNumber: '999',
    invoiceStatus: 'SENT',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'SENT',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
  {
    dueDate: '2024-06-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-06-17',
    fromDate: '2024-06-17',
    toDate: '2024-06-17',
    invoiceNumber: '999',
    invoiceStatus: 'PARTIALLY_PAID',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'PARTIALLY_PAID',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
  {
    dueDate: '2024-03-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-01-17',
    fromDate: '2024-01-17',
    toDate: '2024-03-17',
    invoiceNumber: '999',
    invoiceStatus: 'DEBT_COLLECTION',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'DEBT_COLLECTION',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
  {
    dueDate: '2024-06-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-06-17',
    fromDate: '2024-06-17',
    toDate: '2024-06-17',
    invoiceNumber: '999',
    invoiceStatus: 'PAID_TOO_MUCH',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'PAID_TOO_MUCH',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
  {
    dueDate: '2024-06-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-06-17',
    fromDate: '2024-06-17',
    toDate: '2024-06-17',
    invoiceNumber: '999',
    invoiceStatus: 'REMINDER',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'REMINDER',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
  {
    dueDate: '2024-06-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-06-17',
    fromDate: '2024-06-17',
    toDate: '2024-06-17',
    invoiceNumber: '999',
    invoiceStatus: 'VOID',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'VOID',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
  {
    dueDate: '2024-06-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-06-17',
    fromDate: '2024-06-17',
    toDate: '2024-06-17',
    invoiceNumber: '999',
    invoiceStatus: 'CREDITED',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'CREDITED',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
  {
    dueDate: '2024-06-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-06-17',
    fromDate: '2024-06-17',
    toDate: '2024-06-17',
    invoiceNumber: '999',
    invoiceStatus: 'WRITTEN_OFF',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'WRITTEN_OFF',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
  {
    dueDate: '2024-06-17',
    totalAmount: 814,
    amountVatIncluded: 813.5,
    amountVatExcluded: 651.2,
    vatEligibleAmount: 651.2,
    rounding: 0.5,
    vat: 162.8,
    reversedVat: false,
    pdfAvailable: false,
    currency: 'SEK',
    invoiceDate: '2024-06-17',
    fromDate: '2024-06-17',
    toDate: '2024-06-17',
    invoiceNumber: '999',
    invoiceStatus: 'UNKNOWN',
    ocrNumber: '96758235',
    organizationNumber: 'XXXXXXXXXX',
    invoiceName: 'faktura-999.pdf',
    invoiceType: 'INVOICE',
    invoiceDescription: 'UNKNOWN',
    invoiceAddress: {
      street: 'Storgatangrändvägen 1',
      postcode: '31532',
      city: 'Sundsvall',
      careOf: 'Person',
    },
    facilityId: 'string',
    invoiceOrigin: 'PUBLIC_ADMINISTRATION',
  },
];
