const caseTypeLabelMap: Record<string, string> = {
  MEX_LEASE_REQUEST: 'Arrende/Nyttjanderätt',
  MEX_TERMINATION_OF_LEASE: 'Arrende/Nyttjanderätt, uppsägning',
  MEX_REQUEST_FOR_PUBLIC_DOCUMENT: 'Begäran om allmän handling',
  MEX_BUILDING_PERMIT: 'Bygglov',
  MEX_STORMWATER: 'Dagvatten',
  MEX_INVOICE: 'Faktura',
  MEX_INVASIVE_SPECIES: 'Invasiva arter',
  MEX_HUNTING_LEASE: 'Jakträtt',
  MEX_SELL_LAND_TO_THE_MUNICIPALITY: 'Kommunens inköp av mark',
  MEX_BUY_LAND_FROM_THE_MUNICIPALITY_BUSINESS: 'Köpa kommunal mark, företag',
  MEX_BUY_LAND_FROM_THE_MUNICIPALITY_PRIVATE: 'Köpa kommunal mark, privatperson',
  MEX_LAND_SURVEYING_OFFICE: 'Lantmäteriförrättning',
  MEX_LAND_INSTRUCTION: 'Markanvisning',
  MEX_LAND_RESERVATION: 'Markreservation',
  MEX_LAND_USE_AGREEMENT_VALUATION_PROTOCOL: 'Markupplåtelseavtal/Värderingsprotokoll',
  MEX_LITTERING: 'Nedskräpning',
  MEX_UNAUTHORIZED_RESIDENCE: 'Otillåten bosättning',
  MEX_REFERRAL_CONSULTATION: 'Remiss/Samråd',
  MEX_EASEMENT: 'Servitut',
  MEX_PROTECTIVE_HUNTING: 'Skyddsjakt',
  MEX_SMALL_BOAT_HARBOR_DOCK_PORT: 'Småbåtshamn/Kaj/Hamn',
  MEX_EARLY_DIALOG_PLAN_NOTIFICATION: 'Tidig dialog planbesked',
  MEX_LAND_RIGHT: 'Tomträtt',
  MEX_SQUARE_PLACE: 'Torgplats',
  MEX_TREES_FORESTS: 'Träd, skog',
  UPDATECONTRACT: 'Uppdatera befintligt avtal',
  MEX_PUBLIC_SPACE_LEASE: 'Upplåtelse av allmän/offentlig plats',
  MEX_TRAINING_SEMINAR: 'Utbildning/seminarium',
  MEX_APPLICATION_FOR_ROAD_ALLOWANCE: 'Vägbidrag',
  MEX_ROAD_ASSOCIATION: 'Vägförening/Samfällighetsförening',
  MEX_FORWARDED_FROM_CONTACTSUNDSVALL: 'Ärende från Kontakt Sundsvall',
  MEX_RETURNED_TO_CONTACT_SUNDSVALL: 'Ärende åter till Kontakt Sundsvall',
  MEX_OTHER: 'Övrigt',
  MEX_BUY_LAND_FROM_THE_MUNICIPALITY: 'Köpa kommunal mark',
  MEX_BUY_SMALL_HOUSE_PLOT: 'Köpa småhustomt',
  MEX_REFERRAL_BUILDING_PERMIT_EARLY_DIALOGUE_PLANNING_NOTICE: 'Remiss/Bygglov/Tidig dialog planbesked',

  PARKING_PERMIT: 'Parkeringstillstånd',
  PARKING_PERMIT_RENEWAL: 'Förnyelse av parkeringstillstånd',
  LOST_PARKING_PERMIT: 'Borttappat parkeringstillstånd',
  APPEAL: 'Överklagan',

  PARATRANSIT: 'Ansökan färdtjänst',
  PARATRANSIT_RENEWAL: 'Ansökan fortsatt färdtjänst',
  PARATRANSIT_NATIONAL: 'Ansökan riksfärdtjänst',
  PARATRANSIT_RIAK: 'Ansökan RIAK',
  PARATRANSIT_CHANGE_APPLICATION: 'Ansökan förändring färdtjänst',
  PARATRANSIT_REASSESSMENT_APPLICATION: 'Ansökan omprövning färdtjänst',
  PARATRANSIT_BUS_CARD_APPLICATION: 'Ansökan busskort',

  PARATRANSIT_NOTIFICATION: 'Anmälan färdtjänst',
  PARATRANSIT_NOTIFICATION_RENEWAL: 'Anmälan fortsatt färdtjänst',
  PARATRANSIT_NOTIFICATION_NATIONAL: 'Anmälan riksfärdtjänst',
  PARATRANSIT_NOTIFICATION_RIAK: 'Anmälan RIAK',
  PARATRANSIT_NOTIFICATION_CHANGE: 'Anmälan förändring färdtjänst',
  PARATRANSIT_NOTIFICATION_REASSESSMENT: 'Anmälan omprövning färdtjänst',
  PARATRANSIT_NOTIFICATION_BUS_CARD: 'Anmälan busskort',
};

export function getCaseTypeLabel(caseType?: string): string {
  if (!caseType) return 'Okänd ärendetyp';
  return caseTypeLabelMap[caseType] ?? caseType;
}
